### ISSUE TITLE
When trying to watch non-existing file or directory, report a single error kind instead of the native one

### ISSUE THREAD

**Issue by dfaust** [passcod/notify#110]
Linux: `Io(Error { repr: Os { code: 2, message: "No such file or directory" } })`
Windows: `Generic("Input watch path is neither a file nor a directory.")`
macOS: `PathNotFound`

Any opinions?

**Comment by passcod** [comment]
This will be handled above the backend in v5.

However, it will still be a problem in race conditions when the file disappears between the time the frontend checks for it and the backend attempts to watch it. That will need to be fixed somehow, but I haven't yet figured out what path I want to take for it.

**Comment by passcod** [comment]
This is solved in v5 as file-does-not-exist errors are a specific variant now.

The race condition problem is also solved as both a core and a backend concern. Basically because of #64 and how that's implemented we retry creating backends if it fails on specific paths, without those specific paths.

Closing before v5 release to clear things up a bit.
