### ISSUE TITLE
Rename Chmod event to Metadata

### ISSUE THREAD

**Issue by alexbowers** [passcod/notify#112]
When you `touch` a file, it currently files the chmod, which sounds incorrect (chmod is about permissions on *nix).

An alias to metadata would help code read a little better

**Comment by dfaust** [comment]
I like the idea. But adding another variant to `DebouncedEvent` is not a good solution because we would have to send metadata change events twice and every API user would have to handle them (or get a compiler warning). So we would have to replace the `Chmod` variant.

**Comment by alexbowers** [comment]
Is deprecating the `Chmod` variant an option perhaps, and changing its name to `Metadata` in a future release?

**Comment by passcod** [comment]
Yes. The chmod event is always about file metadata, and never limited to just permissions, so that's a good idea. This is both applicable to Chmod (in DebouncedEvent) and CHMOD (in Op).

I think we should mark those as deprecated and mention that they'll be renamed. Then the actual change should be done whenever the next major goes through. That might be a while, though.

**Comment by alexbowers** [comment]
@passcod Has this been implemented? #114 mentions it was, but I can't see it in code.

**Comment by passcod** [comment]
Err. Hmm. No, I don't think I've done this. The spec in #117 is basically where I wanted to go, with the current release as a "final 4.x version". As in, I could deprecate this particular thing, but if the API is going to radically change anyway... 🤷

Unfortunately I've mostly lost interest in this project, and that plus being very busy at work and elsewhere has my attention _gone_. So notify is in a holding pattern of "it works."

**Comment by passcod** [comment]
This is done in v5, which also brings a different approach to event classification.
