### ISSUE TITLE
CLOSE_WRITE equivalent in DebouncedEvent?

### ISSUE THREAD

**Issue by Boscop** [passcod/notify#115]
Is there a CLOSE_WRITE equivalent in DebouncedEvent? Or will there be one?

My use case is, I want to detect when a new log file in a log dir has been written (completely finished) so that I can do an automatic backup.

Currently I'm using the raw API with this:
```rust
    loop {
        match rx.recv() {
            Ok(RawEvent { path: Some(ref path), op: Ok(op), .. }) if op.contains(CLOSE_WRITE) => {
```

**Comment by dfaust** [comment]
> Is there a CLOSE_WRITE equivalent in DebouncedEvent?

Not exactly. `CLOSE_WRITE` is emitted when a file that was previously opened with the ability to write has been closed. On the other hand the `DebouncedEvent::Write` event is emitted when a file has been written to and no events were detected for the path within the specified time frame.

> Or will there be one?

No, because `CLOSE_WRITE` is only available on linux and `notify` is aimed to be as platform independent as possible. And while adding an extra bit flag to `RawEvent` is not causing much interference, adding a platform dependent event to `DebouncedEvent` would be.

**Comment by Boscop** [comment]
Thanks, so if I want to emulate `CLOSE_WRITE` on windows, I should listen to a `WRITE` event on a file followed by a `CLOSE` event on the same file?

**Comment by dfaust** [comment]
Sorry for the delay.
And no, you can't emulate that on Windows.
The problem is, that all of these file system notification APIs are pretty limited and differ very much between platforms.
The standard way of doing back-ups would be to use the debounced interface and set the notification delay to something reasonable (depends on the use-case). When receiving a `Write` event, start the back-up. When receiving a `NoticeWrite` event while backing up, cancel the backup. I don't think there's a better solution for your problem if you want it to be platform independent.
