### ISSUE TITLE
Watching recursively with inotify fails if a single error is encountered

### ISSUE THREAD

**Issue by dfaust** [passcod/notify#149]
Calling `INotifyWatcher::watch` will fail if an error (like PermissionDenied) is encountered somewhere in the file tree.

So I guess there are two options, either return a list of errors (with file names) or ignore them.

/cc @SirVer

**Comment by passcod** [comment]
I'm leaning more towards returning errors... do you have an opinion?

**Comment by SirVer** [comment]
Swallowing errors is never a good idea, IMHO. I see two options:

1) return `Hash<Path,Error>` for all errors. This implicitly assumes that all paths can fit into a hashmap, i.e. that there are few enough files to watch that they can be hold in memory. I think this assumption is made elsewhere in the code base, so that seems fine tome.
2) let the user pass in a callback for errors. This ships around problem 1 since errors are streamed, but makes the interface more complicated.

I'd go with 1 I think.

**Comment by passcod** [comment]
Yes, we already store the paths plus handles and metadata, so we've always made this assumption.

**Comment by passcod** [comment]
This is done in v5 now so will be solved upon release.
