### ISSUE TITLE
debounced watcher only fires once

### ISSUE THREAD

**Issue by danieleades** [passcod/notify#164]
i'm running the monitor_debounced.rs example, and i can only get the watcher to fire once.
after editing the watched file the first time i get 
```
watching settings.toml
NoticeRemove("/home/dan/Code/notify-test/settings.toml")
```
subsequent edits to the file don't do anything.

i'm on ubuntu 18

**Comment by danieleades** [comment]
using the raw watcher example works as expected-
```
watching settings.toml
WRITE "/home/dan/Code/notify-test/settings.toml" (None)
WRITE "/home/dan/Code/notify-test/settings.toml" (None)
CLOSE_WRITE "/home/dan/Code/notify-test/settings.toml" (None)
```

**Comment by passcod** [comment]
I'm sorry, I don't even really know where to begin debugging this.

- If you set the debounce duration to something smaller, does it help?
- How about larger?
- Speaking of, given the duration in the example is 2 seconds, are you sure you made your file modifications _beyond_ that delay? I.e. could it be that what you're seeing is the notification being... debounced? That's really the only thing I can think of

**Comment by danieleades** [comment]
> I'm sorry, I don't even really know where to begin debugging this.
I'm completely unfamiliar with this package, which is why I started with the examples!
> 
>     * If you set the debounce duration to something smaller, does it help?
I tried 1 second, and 2 seconds with no impact
>     * How about larger?
Not sure, haven't tried this
>     * Speaking of, given the duration in the example is 2 seconds, are you sure you made your file modifications _beyond_ that delay? I.e. could it be that what you're seeing is the notification being... debounced? That's really the only thing I can think of
I tried making file modifications at various timescales with little impact.

The event type seems completely wrong, like the file was being deleted. I checked to see if there were any weird permissions or ownerships of the file, but nothing jumped out at me

**Comment by passcod** [comment]
> The event type seems completely wrong, like the file was being deleted.

Ahaa! Yes. Sorry, I had missed this from your first report.

_This is not a bug._ But it's not a bug for a (to a newcomer) _non-obvious reason_.

What's happening here is two things:

1. Despite this package, and the underlying kernel API, using _paths_ as its inputs (and outputs), they really operate on _inodes_, at least on linux.
2. Some programs (many programs, in fact) instead of writing to a file, prefer to unlink (delete) it, and then write a new one.

The new file would have the same path but _a different inode_. Thus, notify pointed to the original inode does not see any further changes (given it's gone).

The solution for that is to prefer to watch the parent folder, even if you're only interested in a single file.

**Comment by danieleades** [comment]
ah that makes sense! I learnt something new today.
I'm using vim, which creates a new file and copies it on top of the old one by default. I guess then i should be watching the directory, and parsing the filename from the event?
I have to say though, the lack of abstraction from the underlying API kind of breaks the 'cross-platform' element of this crate's description doesn't it? If the `recommended watcher`, and `watcher` structs don't have the same behaviour on every platform, is there another struct in the crate i can use that does?

**Comment by danieleades** [comment]
i'm just being difficult now. Thanks for getting back to me so quickly!

**Comment by passcod** [comment]
File notification is one of the leakiest abstraction in OS tooling, because no two platform APIs have the same behaviour, _even within the same platform_. You can paper over some of it, and this crate does do some of that. It doesn't paper over _this_ inconsistency... if I remember well, because it's not actually an inconsistency, it's how half the platforms work. If anything, it should be disallowed to watch an individual file, a restriction that some similar packages in other languages enforce, but that would probably be annoying for the user.

It's cross-platform in that you don't have to use a different crate with a different API on each platform, and read + interpret the events in _very_ different ways, we do that for you.

I believe we're actually one of the most abstracted lowish level cross platform package for fs notifications. Go's fsnotify is very similar to us, but with less platform support. Node's fs.watch supports more platforms, but does way less papering. Ruby's listen is one of the best! Facebook's watchman has lots of features but no polling. Etc etc etc
