### ISSUE TITLE
CIFS support

### ISSUE THREAD

**Issue by tafia** [passcod/notify#172]
I want to monitor events on a windows server drive mounted on a ubuntu server.

When I use windows (via WSL), everything works fine but when I try to deploy it on our ubuntu server where the same windows server is mounted via cifs, then almost no event is triggered.

The only event I managed to trigger was when doing a touch FROM the server (then triggers a Chmod event). When doing a touch / opening and saving the file, renaming etc from windows, nothing happens.

I don't know exactly what is the problem but I'm leaning towards CIFS. Has someone managed to watch such drives from linux?

**Comment by passcod** [comment]
Inotify does not support CIFS (since around 2009 I think!), so this is a hard no so far. However, there seems to be options around. The two most common workarounds:

- use polling. This has obviously appalling performance.
- run a watcher on the host that issues touches to the linux guest. See for example this fairly recent example and implementation: http://blog.subjectify.us/miscellaneous/2017/04/24/docker-for-windows-watch-bindings.html

A third possibility that would require a bit of engineering would be to write a backend for Notify that listens to events on, say, a UDP or TCP socket, then a Notify consumer that emits those events from the host. That would allow you to use Notify without introducing more traffic down the CIFS link (as touches would do).

A fourth possibility that would however require a lot of engineering and is very much more of a nebulous idea than a hard plausibility is to look into the CIFS kernel support and see if it handles CIFS NOTIFY packets in some way, then hook into those (possibly using eBPF) and write touches to the folder (or send events to a hypothetical Notify backend). This is a _lot_ of work, but short of actually modifying the kernel driver to trigger inotify events (which may actually be easier than this, tbh), would be the only way to support this without running an additional communication channel and tool on the host.

**Comment by tafia** [comment]
Thank you for your answer!

This is what I thought but I wanted to be sure. 

For the best work around, I am not sure yet. For the moment I will find a window server and make it run there.
