### ISSUE TITLE
inotify transitive dependency

### ISSUE THREAD

**Issue by russel** [passcod/notify#176]
When I use notify, I get inotify as a transitive dependency. Seems entirely reasonable. However, inotify has optional dependencies. It seems these are always pulled in when depending on notify. Is there any way of pulling in notify but not pulling in the optional dependencies of inotify?

**Comment by passcod** [comment]
To be clear: Cargo doesn't do "optional dependencies". Deps are marked optional when they're required by features instead of the core code. In inotify's case, the `stream` feature has a bunch of extra dependencies, and that feature is marked as default, so its deps are pulled in.

In our case, we don't actually use inotify's `stream` feature, so I'll go turn that off. Just providing some background because "optional dependencies" may not have the same meaning here as you were thinking of.

**Comment by russel** [comment]
Indeed, my sloppy use of language around "optional", apologies for that. Thank you for making the change and publishing; I now have 31 fewer crates and no loss of functionality!
