### ISSUE TITLE
Generic event delivery mechanism

### ISSUE THREAD

**Issue by jwilm** [passcod/notify#67]
I would like to propose a more flexible event delivery mechanism than the current `mpsc::channel` implementation.
## Motivation

Currently, the only supported way to receive notify events is to use an `mpsc::channel`.

``` rust
let (tx, rx) = mpsc::channel();
let watcher = RecommendedWatcher::new(tx);
match rx.recv() { /* ... /* }
```

If a user wants to deliver events with a different mechanism (eg `mio::Sender<T>`) or even use a different message type with `mpsc::Sender<T>`, an intermediate thread would be needed to proxy the events. This is an unnecessary level of overhead. The following solution should enable delivering events via any mechanism while being equivalent performance-wise with the current implementation.
### Public API

There are two changes to the public API. First, a `Notify` (name bike-shedding needed) trait is added.

``` rust
/// Any type capable of receiving notify events
pub trait Notify : Send + Sync {
    /// An event has been generated, and this function is called to handle it.
    fn notify(&self, notify::Event);
}
```

Second, the `Watcher` trait must be modified to accept a `Notify` instead of an `mpsc::Sender<Event>`.

``` rust
pub trait Watcher<N> {
    /// Create a new Watcher
    fn new(N) -> Result<Watcher<N>, Error>;
    /* other methods same as before */
}
```

For convenience (and ease upgrading from the previous version), a `Notify` implementation based on mpsc channels could be provided.

``` rust
pub struct MpscChannelNotifier(pub mpsc::Sender<Event>);

impl Notify for MpscChannelNotifier {
    #[inline]
    fn notify(&self) {
        let _ = self.0.send(event);
    }
}
```

Upgrading from a previous version with `MpscChannelNotifier` would look like this:

``` rust
let (tx, rx) = mpsc::channel();
// Just adds MpscChannelNotifier
let watcher = RecommendedWatcher::new(MpscChannelNotifier(tx));
```
### Backends

Support for this feature varies by backend
#### FSEvent

With the current implementation, `FsEventWatcher` would need to hold the `Notify` in an `Arc`. The `mpsc::Sender` it holds currently is cloned on each call to watch when a new `StreamContextInfo` is created. Alternatively, `StreamContextInfo` could made `Sync` so that a reference could be held both by the watcher and the context info.
#### Windows

Similar story as FSEvent. The channel is cloned occasionally. 
#### inotify

The `INotifyHandler` type would hold an `Notify` instead of the `mpsc::channel`. The couple of locations where `self.tx.send` is called would be replaced with `self.notifier.notify`

`INotifyWatcher` would need a PhantomData to satisfy the type param of `Watcher`.
#### Polling

The poll watcher currently clones the `mpsc::Sender` at startup, but it doesn't have a use for the sender on the calling thread. This could easily be converted to not use clone and be statically dispatched with a Notify. The type parameter need not be exposed on the `Watcher` type either.
## Unanswered Questions
- Should `notify` return a status? It may occur that a `Notify` becomes unusable (eg MpscChannelNotifier has the recv end hang up), and there would be no point in continuing the watch in that case.
- Should `Notify` require `Clone`, or should it be wrapped in an `Arc` where needed?
- Should `Watcher` actually have the type parameter for `Notify`? The `Notify` type could be boxed instead where needed, and cases like Poll could be statically dispatched from another thread. The type parameter would only be necessary for the `Watcher::new` method.

**Comment by maurizi** [comment]
It might be possible to leverage the `From` / `Into` traits to make this kind of change in a backwards incompatible way.

Instead of `Watcher::new` taking a `Notify`, it would take an `Into<Notify>`.
Implementing `From<Sender<Event>> for MpscChannelNotifier` would let existing callers continue to pass a `mpsc::Sender` without having to change their code.

**Comment by jwilm** [comment]
@maurizi that's a great idea! Sounds like it should work to me.

**Comment by jwilm** [comment]
Hmm, maybe not? [This is as far as I could get](http://is.gd/ymhob0) with an `Into<Notify>` parameter.

**Comment by jwilm** [comment]
It would also be possible to add a separate constructor to keep backwards compatibility. `Watcher::new` would still accept the `Sender<Event>`, and it could delegate to `Watcher::with_notify( ... )`. Whenever we actually need to bump the major, the old version could be removed.

**Comment by jwilm** [comment]
Example with additional constructor: http://is.gd/4qXWIZ

**Comment by passcod** [comment]
Yep, this is pretty much what I meant by "callbacks" in #62, so :+1: :)

**Comment by blaenk** [comment]
Your first one [works](http://is.gd/KWLHld), it's just that you have to annotate the type because it can't be inferred from anything else there. Intuitively I feel like it _should_ infer correctly if you simply annotate `channel::<Event>()`, but that doesn't seem to work. I can't tell if it could possibly be inferred in a real-world context. I think the problem is that there are too many transitive conversions/inferences, but I'm not sure. Even if you "shorten" the conversion path by implementing `Into` directly (and thus not relying on the impl for going from From to Into), [same situation](http://is.gd/IHlrt8).

I know the point was the make this backwards compatible, but I think it would be simpler and more correct to implement `From` for `Watcher` and just using `Watcher::from(tx)`, that's what people tend to expect anyways. Consider this approach: http://is.gd/yhU8Wv . I think this is more idiomatic and simpler, and it really only requires users to change `new` to `from`.

**Comment by jwilm** [comment]
@blaenk 

> I know the point was to make this backwards compatible

Neither type annotations or a `From` impl will help with that. If we want to implement this feature AND are ok breaking backwards compatibility, I agree that `Watcher::from(tx)` is nice. I think the ideal API is exactly what you've proposed.

Since there's a number of other breaking changes in the works (eg #62), maybe we should just plan for the breakage.

**Comment by blaenk** [comment]
> Neither type annotations or a From impl will help with that.

Perhaps I misunderstand, but that's my point. I was saying that I understand that your attempt of @maurizi's suggestion was to remain backwards compatible, i.e. so that a user wouldn't have to change any code at all, but that despite that, I think a `From` impl on `Watcher` would be better.

What I was saying with respect to type annotations was that your playpen sample does work if you explicitly annotate the types. Of course, I understand that if that is a requirement, and code previously hadn't explicitly annotated the type, then indeed it would still be backward incompatible since it would require the user to annotate the type. This is why I wondered if, in a real world scenario, i.e. in existing code, if the type could be inferred and thus wouldn't have to be annotated. I didn't check for that, but my suspicion is it wouldn't work.

But yeah I agree that we should just embrace breakage. This is probably the least of the potential problems too if it just entails going from `new` to `from`.

**Comment by jwilm** [comment]
> Perhaps I misunderstand, but that's my point.

Oops, right. Sorry for the confusion on my end.

> This is probably the least of the potential problems too if it just entails going from new to from

Yeah, pretty easy change

**Comment by lfairy** [comment]
Why can't we `impl Notify for Sender<Event>` directly? Since we define the `Notify` trait, there should be no issues with orphan impls.

**Comment by jwilm** [comment]
Sounds like that should work! Dang... been a while since I've opened this. So much to do and so little time.

**Comment by droundy** [comment]
Why not just accept a closure or function? It would require a new method `new_with_function`, but should be perform equally well, and reduces the cognitive overhead of adding a new trait + `Into/From`.  With the `impl Notify` approach, for instance, using a `mpsc::Channel` with a wrapper type (to support waiting for multiple kinds of events) requires quite a bit of boiler plate code (creating a new named type, and `impl Notify` for that type) as would using a closure, most likely.  Whereas, a closure can handle anything that `impl Notify` can handle with minimal effort.

**Comment by passcod** [comment]
That is my plan for the next major, actually. I'll probably hack on it in December.

**Comment by passcod** [comment]
I think this is covered by v5.
